### PR TITLE
EFFTECH-533 / Stop using Edge branch

### PR DESCRIPTION
**Pull request by yjacquin**
As we're referencing edge branch on editor, it questions us as to why we have not merged this into our fork of master ?

If nothing blocks us from doing so, it is best practice to refer to master / main branches in gemfiles

### CODE REVIEW

**Comment by danielmbarlow** [comment]
@yjacquin For our internal needs I don't mind merging `edge` into `master`, but this is a public repository forked from the OpenCensus project. From memory I think I kept the edge branch so that we could use it without changing `master`. the rationale was that we would be able to keep pulling master from the upstream repo.

However the upstream repo has been or will be abandoned in favour of https://github.com/open-telemetry/opentelemetry-ruby, so I don't think their `master` branch is likely to change, and they aren't likely to accept any more pull requests. That means I think we can merge to `master`

It's possible that someone could depend on our `edge` branch, so I guess we should not delete it.

@apneadiving OK to merge to `master`?

**Comment by danielmbarlow** [comment]
@thomasLeclaire Will our scripts delete `edge` if we merge it?

**Review by danielmbarlow — APPROVED** [review]

**Comment by apneadiving** [comment]
yes why not. Check the .github config to know about deletion

**Comment by thomasLeclaire** [comment]
no @danielmbarlow , edge won't be removed, no such settings on this repo. 

However, if upstream repo is deprecated, it's anyway not good idea to use such master! we should migrate to the new repo to use I think

**Comment by danielmbarlow** [comment]
Yes. We need to move to the new library when we know it is fully featured and stable. I'll see if we can create a ticket for that.

**Pull request merged**
